version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - ./public/uploads:/usr/src/app/public/uploads
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=sonatrach_files
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    depends_on:
      - db
    command: sh -c "npm install --legacy-peer-deps && npm run dev"

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: sonatrach_files
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  db_data:
